accounts/urls.py
from django.conf.urls import url
from . import views

app_name ='accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout")
    
    
    
]

home/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name ='home'
urlpatterns = [
    url(r'^$', views.home, name= "home"),
    url(r'^home/identfay/$', views.identfay),
    url(r'^home/medical/$', views.medical, name= "medical"),
    url(r'^age_cal/$', views.age_cal, name= "age_cal"),
    url(r'^home/register/$', views.register),
    url(r'^homeaddFace/$', views.addFace),
    url(r'^home/welcome/(?P<face_id>\d+)/$', views.welcome)
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings, urls
from . import views, settings  
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'', include('home.urls')),
   # url(r'^media/(?p<path>.*)$',serve{'document_root' : settings.MEDIA_ROOT}),
    #url(r'^static/(?p<path>.*)$',serve{'document_root' : settings.STATIC_ROOT}),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse 
from datetime import datetime, date
from django.db.models.signals import post_save
from django.utils.timezone import now
import uuid
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils import timezone
from .managers import CustomUserManager
from  datetime import date
from bootstrap_datepicker_plus import DatePickerInput

sex_choice = (
     ('Male', 'Male'),
     ('Female', 'Female')
 )
class UserProfile(models.Model):
    user = models.OneToOneField(User, null='True', on_delete = models.CASCADE)
    face_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=sex_choice, default='Male')
    date_of_birth = models.DateField(default=timezone.now)
    job = models.CharField(max_length = 15)
    phone = models.CharField(max_length =  10)
    religion = models.CharField(max_length = 100)
    region = models.CharField(max_length = 20)
    zone = models.CharField(max_length = 20)
    woreda = models.CharField(max_length = 20)
    kebele = models.CharField(max_length = 200)
    image = models.ImageField(default='default.jpg', upload_to="profile_image/", blank=False)
    mother_name = models.CharField(max_length = 200)
    emergnency_case = models.CharField(max_length = 200)
    emergnency_number = models.CharField(max_length = 200)
    DisplayFields = ['name', 'gender', 'age', 'job', 'phone', 'religion', 'region', 'zone', 'woreda', 'kebele', 'image', 'mother_name', 'emergnency_case', 'emergnency_number']
    SearchableFields = ['face_id', 'phone']


     
    def __str__(self):
        return self.name 
# Create your models here.
    @property
    def age(self):
        if (self.date_of_birth != None):
            age = date.today().year -self.date_of_birth.year
            return age
    

home/forms.py
from django import forms
from .models import * 
#from home.models importUserProfile

class RegisterForm(forms.ModelForm):

    class Meta:
        model =UserProfile
        fields = ( 'face_id', 'name', 'gender', 'date_of_birth', 'job', 'phone', 'religion', 'region', 'zone', 'woreda', 'kebele', 'image', 'mother_name', 'emergnency_case', 'emergnency_number' )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
def signup_view(request):
    if request.method =="POST":
        form= UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = login(request, user)
            return redirect('home:home')

    else:
       form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method =="POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user= form.get_user()
            login(request, user)
            if'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
              return redirect('home:home')

    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method =="POST":
        logout(request)
        return redirect('home:home')

home/views.py
from django.shortcuts import render, redirect
from home.forms import RegisterForm
from django.contrib import messages
from home.backEnd import FaceRecognition
from home.models import UserProfile
from django.contrib.auth.decorators import login_required
import datetime

facerecognition = FaceRecognition()

def home(request):
    return render(request, 'home/home.html')
@login_required
def register(request):
    if request.method =='POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, 'Successfully Registerd!')
            addFace(request.POST['face_id'])
            return redirect('/')
        else:
            messages.error(request, "Account Register Failed!")

    form = RegisterForm()
    context = {
        'title' : 'Register Form',
        'form' : form
    }
    return render(request, 'home/register.html', context)
def age_cal(request, date_of_birth):
    date_of_birth = date_of_birth
    todayy = datetime.datetime.now()
    age= int(todayy - date_of_birth)
    return render(request, 'home/profile.html', {'age': age} )

def addFace(face_id):
    face_id = face_id
    facerecognition.faceDetect(face_id)
    facerecognition.trainFace()
    return redirect('/')

@login_required
def identfay(request):
    face_id = facerecognition.recognizeFace()
    print(face_id)
    return redirect('/home/welcome/'+ str(face_id))

def welcome(request, face_id):
    face_id = int(face_id)
    print(face_id)
    data = {
        'user':UserProfile.objects.get(face_id= face_id)
    }
    return render(request, 'home/profile.html', data)
@login_required
def medical(request):
    return render(request, 'home/medical.html')
def age(self):
        return int((datetime.now().date() - self.date_of_birth).days / 365.25)

website/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/home/')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
    <h1>Login</h1>
    <form class="site-form" action="/accounts/login/" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
           <input type="hidden" name="next" value="{{ request.GET.next}}">
        {% endif %}
        <button type="submit">login</button>
    </form>
    
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    {% if user.userprofile.image %}
    <img src="{{ user.userprofile.image.url }}" width="240">
    {% endif %}
</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block body %}
    <h1>Signip</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
    
{% endblock %}

accounts/templates/base.html
{% load static from statics %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
  <header class="wrapper">
    <h1> <a href ="{% url 'home:home'%}"><img src="{%static 'logo.png'%}" alt="djangonautic"></a></h1>
    <nav>
      <ul>
        <li>
          <form class="logout-link" action="{% url 'accounts:logout'%}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
      </ul>
    </nav>
  </header>
  <div class="wrapper">
    {% block content %}
    {% endblock %}
  </div>
  </body>
</html>

home/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    {% block head %}
    <title>BASE</title>
    {% endblock %}
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8">
	
	<!-- Font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700%7CPoppins:400,500" rel="stylesheet">
	<link rel="stylesheet" href="/static/common-css/bootstrap.css">
	<link href="/static/common-css/ionicons.css" rel="stylesheet">
	<link rel="stylesheet" href="/static/common-js/jquery.classycountdown.js" />	
	<link href="/static/css/styles.css" rel="stylesheet">
	<link href="/static/css/responsive.css" rel="stylesheet">
</head>
<body background="/static/images/pic6.jpg">
	<h1> <a href ="{% url 'home:home'%}"><img src="{%static 'logo.png'%}" alt="djangonautic"></a></h1>
    <nav>
      <ul>
        <li>
          <form class="logout-link" action="{% url 'accounts:logout'%}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
      </ul>
    </nav>
  </header>
	
	<div class="main-area-wrapper" style="background-image:url(/static/images/pic6.jpg);">
		<div class="main-area center-text" >
			{% block body %}
			<h1>BASE TEMPLATE</h1>
			{% endblock %}
		</div><!-- main-area -->
	</div><!-- main-area-wrapper -->
	
	<!-- SCIPTS -->
	
	<script src="/static/common-js/jquery-3.1.1.min.js"></script>
	
	<script src="/static/common-js/jquery.countdown.min.js"></script>
	
	<script src="/static/common-js/scripts.js"></script>
	
	
</body>
</html>

home/templates/basee.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
  <header class="wrapper">
    <h1> <a href ="{% url 'home:home'%}"><img src="{%static 'logo.png'%}" alt="djangonautic"></a></h1>
    <nav>
      <ul>
        <li>
          <form class="logout-link" action="{% url 'accounts:logout'%}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
      </ul>
    </nav>
  </header>
  <div class="wrapper">
    {% block content %}
    {% endblock %}
  </div>
  </body>
</html>

home/templates/home/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

home/templates/home/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<div class="display-table">
    <div class="display-table-cell">
        
        <h1 class="title"><b>Ethiopian Citizen Identfication Platform </b></h1>
        <p class="desc font-white"></p>
    
        <a class="notify-btn" href="/home/register/"><b>Register</b></a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a class="notify-btn" href="/home/identfay/"><b>identfay</b></a>
        
        
    </div><!-- display-table -->
</div><!-- display-table-cell -->

{% endblock %}

home/templates/home/identfay.html
{% extends "main/base.html" %}

{% block title %}
Login Here
{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
     <form method="post" class="from-group">
	{% csrf_token %}
	{{form|crispy}}
	<p>Don't have an accoount? Create one <a href="/register">here</a></p>
	<button type="submit" class="btn btn-success">identfay</button>	
    </form>
{% endblock %}

home/templates/home/medical.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>link to domain specfic information like medical record, criminal record... </h1>
    
</div>
{% endblock %}

home/templates/home/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
<link href="/static/css/profile.css" rel="stylesheet">
<link rel="stylesheet" href="/static/linericon/style.css">
<style>
    .topright {
        position: absolute;
        top: 8px;
        right: 16px;
        font-size: 14px;
    }
    h1, h2, h3, h4, h5, p, li, div{
        color: black;
        align-items: left;
    }
    img {
        max-width: 100%;
        max-height: 100%;
    }
</style>
<script>
    function age (date_of_birth)
    {
        var date_of_birth = new Date(Document.getElemnetById("date_of_birth").value);
        var date_of_birth_day = date_of_birth.getDate();
        var date_of_birth_month = date_of_birth.getMonth();
        var date_of_birth_year = date_of_birth.getFullYear();

        var today_date = new Date();
        var today_day = today_date.getDate();
        var today_month = today_month.getMonth();
        var today_year = today_year.getFullYear();

        var cal_age = 0;
        if (today_month > date_of_birth_month) cal_age = to - date_of_birth_year;
        else if (today_month==date_of_birth_month)
        {
            if (today_day >= date_of_birth_day) cal_age = today_year - date_of_birth_year;
            else cal_age = today_year - date_of_birth_year - 1;
        }
        else cal_age = today_year - date_of_birth_year - 1;
        var output_value = cal_age;
        document.getElemnetById("cal_age").innerHTML = cal_age;
    }
</script>
{% endblock %}
{% block body %}
<div class="container-profile">
    <a class="notify-btn topright" href="/home"> Go Home </a> 
    <div class="wrap-profile">
        <div class="row">
            <div class="col-4">
                {% if user.image %}
                   <img src="{{ user.image.url }}">
                {% else %}
                    <img src="/static/images/dp.jpeg">
                {% endif %}
            </div>
            <div class="col-1"></div>
            <div class="col-7">
                <p>Full name: {{ user.name }}</p>
                <p>Sex: {{ user.gender }}</p>
                <p>age:  {{ user.age }}</p>
                <p>Job: {{ user.job }}</p>
                <p>phone: {{ user.phone }}</p>
                <p>religion: {{ user.religion }}</p>
                <p>region: {{ user.region }}</p>
                <p>zone: {{ user.zone }}</p>
                <p>woreda: {{ user.woreda }}</p>
                <p>kebele: {{ user.kebele }}</p>
                <p>mother name: {{ user.mother_name }}</p>
                <p>emergnency case: {{ user.emergnency_case }}</p>
                <p>emergnency number: {{ user.emergnency_number }}</p>
                <a href="/home/medical/"><b>morre detail</b></a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a class="notify-btn" href="/home/"><b>Home</b></a>
            </ul>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

home/templates/home/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% block head %}
<title>Register</title>
<link href="/static/css/form.css" rel="stylesheet">
<style>
    .topright {
        position: absolute;
        top: 8px;
        right: 16px;
        font-size: 14px;
    }
    label{
        background: transparent;
        font-family: Raleway-SemiBold;
        font-size: 18px;
        color: #333333;
        line-height: 1.2;
    }
</style>
{% endblock %}

{% block body %}
<div class="container-contact100"> 
    <a class="notify-btn topright" href="/"> Go Home
    </a>       
    <div class="wrap-contact100">
        <form class="contact100-form validate-form" action="/home/register/" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <span class="contact100-form-title">
                Register Form
            </span>

            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="name" placeholder="Full Name" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="number" name="face_id" placeholder="ID [Must be a number]" required>
                <span class="focus-input100"></span>
            </div> 
            <label for="gender">Sex:</label>
            <select name="gender" id="gender">
              <option value="Male">Male</option>
              <option value="Female">Female</option>
            </select>
            <div class="wrap-input100 validate-input">
                <label for="date_of_birth">Birthday:</label>
            <input type="date" id="date_of_birth" name="date_of_birth"> 
                <span class="focus-input100"></span>
            </div> 
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="job" placeholder="Occupation" required>
                <span class="focus-input100"></span>
            </div> 

            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="phone" placeholder="Telephone" required>
                <span class="focus-input100"></span>
            </div> 
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="religion" placeholder="Religion" required>
                <span class="focus-input100"></span>
            </div>
            
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="region" placeholder="Region" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="zone" placeholder="Zone" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="woreda" placeholder="Woreda" required>
                <span class="focus-input100"></span>
            </div>
            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="kebele" placeholder="Kebele" required>
                <span class="focus-input100"></span>
            </div> 
            
            <div class="wrap-input100  validate-input">
                <input class="input100" type = "file" name = "image" style = "margin-left:20%;" 
                placeholder = "Picture"  />
            </div> 

            <div class="wrap-input100 rs1 validate-input">
                <input class="input100" type="text" name="mother_name" placeholder="Mothers Full Name" required>
                <span class="focus-input100"></span>
            </div> 

            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="emergnency_case" placeholder="Emergency Case" required>
                <span class="focus-input100"></span>
            </div> 

            <div class="wrap-input100 validate-input">
                <input class="input100" type="text" name="emergnency_number" placeholder="Emergnency Number" required>
                <span class="focus-input100"></span>
            </div> 

            <div class="container-contact100-form-btn">
                <button type="submit" class="notify-btn">
                    <span>
                        Register
                    </span>
                </button>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <button type="reset" class="notify-btn">
                        <span>
                            Clear
                        </span>
                    </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% endblock %}

home/templates/home/welcome.html
{% extends 'base.html' %}

{% block head %}
<title>Home</title>
<style>
    .topright {
        position: absolute;
        top: 8px;
        right: 16px;
        font-size: 14px;
    }
</style>
{% endblock %}

{% block body %}
<div class="display-table">
    <div class="display-table-cell">
            <a class="notify-btn topright" href="home/"> Go Home
            </a>
        
        <h1 class="title"><b>Welcome {{user.name}}</b></h1>
        
    </div><!-- display-table -->
</div><!-- display-table-cell -->

{% endblock %}